#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t AOKP"

$L "******************************************"
$L "*    Project Kang By IPSBHANGU 	     *"
$L "******************************************"
$L "An Project For Feature Lovers"
$L "`getprop ro.build.version.release` / KANG-`getprop ro.kang.version`";
